GET http://localhost:3003/api/blogs

###

DELETE http://localhost:3003/api/blogs/601efc89ade44b02155ece45
Authorization: 

###
POST http://localhost:3003/api/blogs 
content-type: application/json
Authorization: 

{
  "title": "me again",
  "author": "bob5",
  "url": "http://allaboutbob.me",
  "likes": 10
}

###

POST http://localhost:3003/api/users
content-type: application/json
Authorization: 

{
  "username": "malcolm3",
  "name": "malcolm3 macleod3",
  "password": "passowrd23"
}



###
GET http://localhost:3003/api/users
Authorization: 

###

POST http://localhost:3003/api/login
content-type: application/json

{
  "username": "malcolm3",
  "password": "passowrd23"
}

###

POST http://localhost:3003/api/blogs 
content-type: application/json
Authorization: 

{
  "title": "me again",
  "author": "bob5",
  "url": "http://allaboutbob.me",
  "likes": 10
}

###
DELETE http://localhost:3003/api/blogs/6029bcf2b7a0c1638b510ae
Authorization: 